log:
  disable_sentry: true
  level: "info"

db:
  url: "postgres://postgres:postgres@staff_db/postgres?sslmode=disable"
# Uncomment to use locally:
#  url: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"

listener:
  addr: :9102

endpoints:
  docker: true
  services:
    - service: "auth_service"
      entry_points:
        - "localhost:9110/jwt/login"
        - "auth_service:9110/jwt/login"


cop:
  disabled: true