version: '3.3'

services:
  staff-service:
    restart: unless-stopped
    build: .
    ports:
      - "9102:9102"
    depends_on:
      - staff_db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./config.yaml:/config.yaml
    command: run service

  staff_db:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - database_data:/var/lib/postgresql/data

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local